name: install_build/

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_call:
    inputs:
      access_token:
        required: true
        type: string

jobs:
  install_builde:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Rebuild the public/ directory
        run: |
           bash extractMuiVersion.sh
           
      - name: build
        run: yarn build

      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2

        with:
          access-token: ${{ secrets.PAT_TOKEN }}
          github_token: ${{ secrets.PAT_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths

           
