name: installDependence/

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  install-dependence:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Rebuild the public/ directory
        run: |
           bash extractMuiVersion.sh && gatsby build


      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: public
          path: public/

     
