name: installCode/

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  installCode:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: extractMuiVersion
        run: |
           bash extractMuiVersion.sh 
           

      - name: Rebuild the public/ directory
        run: |
          yarn build
      - name: Compare the expected and actual public/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol public/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: public
          path: public/
