name: installCode/

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  installCode:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: extractMuiVersion
        run: |
           bash extractMuiVersion.sh 
           


      - name: Rebuild the dist/ directory
        run: |
          yarn build
          yarn package
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
